import type { UnpluginFactory } from 'unplugin'
import type { ResolvedConfig } from '../config/resolve'
import type { MediaConfig } from '../types/config'
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, join, resolve as resolvePath, sep } from 'node:path'
import process from 'node:process'
import { createUnplugin } from 'unplugin'
import { resolveConfig } from '../config/resolve'
import { checkContent } from '../disk/check'
import { loadConfig } from '../disk/config'
import { findRoot } from '../disk/root'
import { ContentError } from '../files/issues'
import { ENDPOINT } from '../files/paths'
import { handle } from './endpoint'
import { ENTRY_PREFIX, findCollection, generateEntry, generateList, generateRoot, LIST_PREFIX, resolved, VIRTUAL_ID } from './modules'

export interface Options {
  root?: string
  write?: boolean
  media?: MediaConfig
}

const TYPES = `// Generated by ForgePress. Do not edit.
import type schema from './schema'

declare module 'forgepress' {
  interface ForgePressSchemaRegistry {
    schema: typeof schema
  }
}

export {}
`

function writeTypes(root: string, config: ResolvedConfig): void {
  const path = join(root, config.paths.types)
  const current = existsSync(path) ? readFileSync(path, 'utf8') : undefined

  if (current === TYPES)
    return

  mkdirSync(dirname(path), { recursive: true })
  writeFileSync(path, TYPES)
}

export const unpluginFactory: UnpluginFactory<Options | undefined> = (options) => {
  let root = options?.root ? resolvePath(options.root) : findRoot(process.cwd())
  let local = false
  let serving = false
  let reported = ''

  let config: Promise<ResolvedConfig> | undefined

  async function load(): Promise<ResolvedConfig> {
    const loaded = await loadConfig(root)

    return resolveConfig({ ...loaded, media: { ...loaded?.media, ...options?.media } })
  }

  function resolve(): Promise<ResolvedConfig> {
    config ??= load()

    return config
  }

  return {
    name: 'unplugin-forgepress',

    vite: {
      configResolved(resolvedConfig) {
        root = options?.root ? resolvePath(resolvedConfig.root, options.root) : findRoot(resolvedConfig.root)
        serving = resolvedConfig.command === 'serve'
        local = serving && options?.write !== false
      },

      async configureServer(server) {
        const current = await resolve()

        function invalidate(): void {
          const stale = [...server.moduleGraph.idToModuleMap.entries()]
            .filter(([id]) => id.startsWith(resolved('virtual:forgepress/')))
            .map(([, module]) => module)

          if (stale.length === 0)
            return

          for (const module of stale)
            server.moduleGraph.invalidateModule(module)

          server.ws.send({ type: 'full-reload' })
        }

        const { logger } = server.config
        let pending: ReturnType<typeof setTimeout> | undefined

        async function report(): Promise<void> {
          const issues = await checkContent(root, current.paths)
          const message = issues.length > 0 ? new ContentError(issues).message : ''

          if (message === reported)
            return

          if (message)
            logger.warn(`${message}\n[forgepress] the build fails until ${issues.length === 1 ? 'this problem is' : 'these problems are'} fixed`, { timestamp: true })
          else
            logger.info('[forgepress] content problems are fixed', { timestamp: true })

          reported = message
        }

        function check(): void {
          clearTimeout(pending)

          pending = setTimeout(() => {
            report().catch((error: unknown) => logger.error(`[forgepress] could not check the content: ${error instanceof Error ? error.message : String(error)}`))
          }, 100)
        }

        const schemaFile = join(root, current.paths.schema)
        const contentDir = join(root, current.paths.content)

        function watch(file: string): void {
          if (file !== schemaFile && !file.startsWith(`${contentDir}${sep}`))
            return

          invalidate()
          check()
        }

        server.watcher.add([schemaFile, contentDir])
        server.watcher.on('add', watch)
        server.watcher.on('change', watch)
        server.watcher.on('unlink', watch)

        check()

        if (options?.write === false)
          return

        server.middlewares.use((request, response, next) => {
          const method = request.method ?? ''
          const handled = method === 'POST' || method === 'DELETE' || method === 'GET'

          if (!handled || !request.url?.startsWith(`${ENDPOINT}/`))
            return next()

          handle(current, root, request, response)
            .then(invalidate)
            .catch((error: unknown) => {
              response.statusCode = 500
              response.end(error instanceof Error ? error.message : String(error))
            })
        })
      },
    },

    async buildStart() {
      const current = await resolve()

      writeTypes(root, current)

      if (serving)
        return

      const issues = await checkContent(root, current.paths)

      if (issues.length > 0)
        throw new ContentError(issues)
    },

    resolveId(id) {
      if (id === VIRTUAL_ID || id.startsWith(LIST_PREFIX) || id.startsWith(ENTRY_PREFIX))
        return resolved(id)
    },

    async load(id) {
      const current = await resolve()

      if (id === resolved(VIRTUAL_ID))
        return generateRoot(root, local, current)

      if (id.startsWith(resolved(LIST_PREFIX))) {
        const collection = findCollection(root, current, id.slice(resolved(LIST_PREFIX).length))

        return collection ? generateList(collection) : 'export default []\n'
      }

      if (id.startsWith(resolved(ENTRY_PREFIX)))
        return generateEntry(root, current, id.slice(resolved(ENTRY_PREFIX).length))
    },
  }
}

export const unplugin = /* #__PURE__ */ createUnplugin(unpluginFactory)

export default unplugin

export const vitePlugin = unplugin.vite
export const rollupPlugin = unplugin.rollup
export const rolldownPlugin = unplugin.rolldown
export const webpackPlugin = unplugin.webpack
export const rspackPlugin = unplugin.rspack
export const farmPlugin = unplugin.farm
export const bunPlugin = unplugin.bun
