import type { ServerResponse } from 'node:http'
import type { UnpluginFactory } from 'unplugin'
import type { ResolvedConfig } from '../config/resolve'
import type { MediaConfig } from '../types/config'
import type { ContentIssue } from '../types/issues'
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { readFile } from 'node:fs/promises'
import { dirname, isAbsolute, join, relative, resolve as resolvePath, sep } from 'node:path'
import process from 'node:process'
import { createUnplugin } from 'unplugin'
import { resolveConfig } from '../config/resolve'
import { loadConfig } from '../disk/config'
import { buildOutput, outputDir } from '../disk/output'
import { OUTPUT_VARIABLE } from '../disk/reader'
import { findRoot } from '../disk/root'
import { ContentError } from '../files/issues'
import { ENDPOINT } from '../files/paths'
import { errorMessage } from '../utils/error'
import { EndpointError, handle } from './endpoint'
import { generateSettings, resolved, SETTINGS_ID } from './settings'

export interface Options {
  root?: string
  write?: boolean
  media?: MediaConfig
}

const TYPES = `// Generated by ForgePress. Do not edit.
import type schema from './schema'

declare module 'forgepress' {
  interface ForgePressSchemaRegistry {
    schema: typeof schema
  }
}

export {}
`

function writeTypes(root: string, config: ResolvedConfig): void {
  const path = join(root, config.paths.types)
  const current = existsSync(path) ? readFileSync(path, 'utf8') : undefined

  if (current === TYPES)
    return

  mkdirSync(dirname(path), { recursive: true })
  writeFileSync(path, TYPES)
}

function inside(parent: string, child: string): boolean {
  const path = relative(parent, child)

  return path !== '' && path !== '..' && !path.startsWith(`..${sep}`) && !isAbsolute(path)
}

async function sendOutput(response: ServerResponse, file: string): Promise<void> {
  try {
    const text = await readFile(file)

    response.setHeader('Content-Type', 'application/json')
    response.setHeader('Cache-Control', 'no-cache')
    response.end(text)
  }
  catch {
    response.statusCode = 404
    response.end()
  }
}

export const unpluginFactory: UnpluginFactory<Options | undefined> = (options) => {
  let root = options?.root ? resolvePath(options.root) : findRoot(process.cwd())
  let local = false
  let serving = false
  let publicDir = ''

  let config: Promise<ResolvedConfig> | undefined

  async function load(): Promise<ResolvedConfig> {
    const loaded = await loadConfig(root)

    return resolveConfig({ ...loaded, media: { ...loaded?.media, ...options?.media } })
  }

  function resolve(): Promise<ResolvedConfig> {
    config ??= load()

    return config
  }

  return {
    name: 'unplugin-forgepress',

    vite: {
      configResolved(resolvedConfig) {
        root = options?.root ? resolvePath(resolvedConfig.root, options.root) : findRoot(resolvedConfig.root)
        serving = resolvedConfig.command === 'serve'
        local = serving && options?.write !== false
        publicDir = resolvedConfig.publicDir ?? ''
      },

      async configureServer(server) {
        const current = await resolve()
        const { logger } = server.config
        const output = outputDir(root, current)
        let reported = ''

        process.env[OUTPUT_VARIABLE] = output
        let pending: ReturnType<typeof setTimeout> | undefined

        function report(issues: readonly ContentIssue[]): void {
          const message = issues.length > 0 ? new ContentError(issues).message : ''

          if (message === reported)
            return

          if (message)
            logger.warn(`${message}\n[forgepress] the build fails until ${issues.length === 1 ? 'this problem is' : 'these problems are'} fixed`, { timestamp: true })
          else
            logger.info('[forgepress] content problems are fixed', { timestamp: true })

          reported = message
        }

        async function refresh(): Promise<void> {
          try {
            report((await buildOutput(root, current, { dev: true })).issues)
          }
          catch (error) {
            if (!(error instanceof ContentError))
              throw error

            report(error.issues)
          }
        }

        function reload(): void {
          server.ws.send({ type: 'full-reload' })
        }

        function schedule(): void {
          clearTimeout(pending)

          pending = setTimeout(() => {
            refresh()
              .catch((error: unknown) => logger.error(`[forgepress] could not write the content output: ${errorMessage(error)}`))
              .finally(reload)
          }, 100)
        }

        const schemaFile = join(root, current.paths.schema)
        const contentDir = join(root, current.paths.content)

        function watch(file: string): void {
          if (file === schemaFile || file.startsWith(`${contentDir}${sep}`))
            schedule()
        }

        server.watcher.add([schemaFile, contentDir])
        server.watcher.on('add', watch)
        server.watcher.on('change', watch)
        server.watcher.on('unlink', watch)

        await refresh().catch((error: unknown) => logger.error(`[forgepress] could not write the content output: ${errorMessage(error)}`))

        if (publicDir && inside(publicDir, output)) {
          const prefix = `/${relative(publicDir, output).split(sep).join('/')}/`

          server.middlewares.use((request, response, next) => {
            const path = decodeURIComponent(request.url?.split('?')[0] ?? '')

            if ((request.method !== 'GET' && request.method !== 'HEAD') || !path.startsWith(prefix))
              return next()

            const file = join(output, path.slice(prefix.length))

            if (!inside(output, file)) {
              response.statusCode = 404
              response.end()

              return
            }

            void sendOutput(response, file)
          })
        }

        if (options?.write === false)
          return

        server.middlewares.use((request, response, next) => {
          const method = request.method ?? ''
          const handled = method === 'POST' || method === 'DELETE' || method === 'GET'

          if (!handled || !request.url?.startsWith(`${ENDPOINT}/`))
            return next()

          handle(current, root, request, response)
            .then(() => {
              if (method !== 'GET')
                schedule()
            })
            .catch((error: unknown) => {
              response.statusCode = error instanceof EndpointError ? error.status : 500
              response.end(errorMessage(error))
            })
        })
      },
    },

    async buildStart() {
      const current = await resolve()

      writeTypes(root, current)

      if (serving)
        return

      process.env[OUTPUT_VARIABLE] = outputDir(root, current)
      await buildOutput(root, current)
    },

    resolveId(id) {
      if (id === SETTINGS_ID)
        return resolved(id)
    },

    async load(id) {
      if (id === resolved(SETTINGS_ID))
        return generateSettings(local, await resolve())
    },
  }
}

export const unplugin = /* #__PURE__ */ createUnplugin(unpluginFactory)

export default unplugin

export const vitePlugin = unplugin.vite
export const rollupPlugin = unplugin.rollup
export const rolldownPlugin = unplugin.rolldown
export const webpackPlugin = unplugin.webpack
export const rspackPlugin = unplugin.rspack
export const farmPlugin = unplugin.farm
export const bunPlugin = unplugin.bun
