import type { ResolvedConfig } from '../config/resolve'
import type { MediaConfig } from '../config/types'
import { existsSync, mkdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs'
import { dirname, join, resolve } from 'node:path'
import process from 'node:process'
import { resolveConfig } from '../config/resolve'
import { loadConfig } from '../disk/config'
import { outputDir } from '../disk/output'
import { OUTPUT_VARIABLE } from '../disk/reader'
import { findRoot } from '../disk/root'

export interface Options {
  root?: string
  write?: boolean
  media?: MediaConfig
}

export interface Project {
  root: string
  config: ResolvedConfig
  output: string
}

const TYPES = `// Generated by ForgePress. Do not edit.
import type schema from './schema'

declare module 'forgepress' {
  interface ForgePressSchemaRegistry {
    schema: typeof schema
  }
}

export {}
`

export async function loadProject(base: string, options?: Options): Promise<Project> {
  const root = options?.root ? resolve(base, options.root) : findRoot(base)
  const loaded = await loadConfig(root)
  const config = resolveConfig({ ...loaded, media: { ...loaded?.media, ...options?.media } })
  const output = outputDir(root, config)

  process.env[OUTPUT_VARIABLE] = output

  return { root, config, output }
}

export function syncTypes(root: string, config: ResolvedConfig): void {
  const path = join(root, config.paths.types)

  if (!existsSync(join(root, config.paths.schema))) {
    rmSync(path, { force: true })

    return
  }

  if (existsSync(path) && readFileSync(path, 'utf8') === TYPES)
    return

  mkdirSync(dirname(path), { recursive: true })
  writeFileSync(path, TYPES)
}
