import type { ResolvedConfig } from '../config/resolve'
import type { MediaConfig } from '../types/config'
import { existsSync, mkdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { resolveConfig } from '../config/resolve'
import { loadConfig } from '../disk/config'

export interface Options {
  root?: string
  write?: boolean
  media?: MediaConfig
}

const TYPES = `// Generated by ForgePress. Do not edit.
import type schema from './schema'

declare module 'forgepress' {
  interface ForgePressSchemaRegistry {
    schema: typeof schema
  }
}

export {}
`

export async function loadProjectConfig(root: string, options?: Options): Promise<ResolvedConfig> {
  const loaded = await loadConfig(root)

  return resolveConfig({ ...loaded, media: { ...loaded?.media, ...options?.media } })
}

export function syncTypes(root: string, config: ResolvedConfig): void {
  const path = join(root, config.paths.types)

  if (!existsSync(join(root, config.paths.schema))) {
    rmSync(path, { force: true })

    return
  }

  if (existsSync(path) && readFileSync(path, 'utf8') === TYPES)
    return

  mkdirSync(dirname(path), { recursive: true })
  writeFileSync(path, TYPES)
}
