import type { ForgePressEntry } from 'forgepress'

export default {
  id: 'page_171d7d040350',
  status: 'published',
  createdAt: '2026-09-15T12:34:34.160Z',
  updatedAt: '2026-09-15T14:04:45.103Z',
  title: 'Next.js',
  slug: '/next',
  content: 'Install ForgePress, and Vue for the editor:\n\n```sh\npnpm add forgepress vue\n```\n\nWrap the configuration in `next.config.ts` with `withForgePress`:\n\n```ts\nimport { withForgePress } from \'forgepress/next\'\n\nexport default withForgePress({\n  output: \'export\',\n})\n```\n\n`withForgePress` does what the Vite plugin does for other frameworks. It writes the content output during `next build` and while `next dev` runs, adds your content folder to `tsconfig.json` so TypeScript knows the schema, and gives the editor its settings. While `next dev` runs, a small server on your machine reads and writes your content files for the editor and reloads open pages after every change. It only answers pages opened on `localhost`, so open the editor there, not at your network address. Turbopack and webpack both work.\n\nQuery content in server components:\n\n```tsx\nimport { query } from \'forgepress\'\nimport { Posts } from \'./posts\'\n\nexport default async function Page() {\n  return <Posts posts={await query(\'blogPost\').locale(\'en\').sort(\'createdAt\', \'desc\')} />\n}\n```\n\nThe editor is a client component you add yourself, for example `app/admin/page.tsx`:\n\n```tsx\n\'use client\'\n\nimport { mountEditor } from \'forgepress/editor\'\nimport { useEffect, useRef } from \'react\'\n\nexport default function Admin() {\n  const host = useRef<HTMLDivElement>(null)\n\n  useEffect(() => mountEditor(host.current), [])\n\n  return <div ref={host} />\n}\n```\n\n## Preview\n\nServer components run when the site is built, so what they render can\'t change in the browser. To let editors preview content that isn\'t published yet, pass the content to a client component and load it there again with `usePreviewData`. Visitors see the content from the build and nothing extra is loaded; editors who are signed in see the preview, which updates whenever they change something.\n\n```tsx\n\'use client\'\n\nimport type { ForgePressOutput } from \'forgepress\'\nimport { query } from \'forgepress\'\nimport { usePreviewData } from \'forgepress/react\'\n\nexport function Posts({ posts }: { posts: ForgePressOutput<\'blogPost\'>[] }) {\n  const shown = usePreviewData(posts, () => query(\'blogPost\').locale(\'en\').sort(\'createdAt\', \'desc\'))\n\n  return <ul>{shown.map(post => <li key={post.id}>{post.title}</li>)}</ul>\n}\n```\n\nContent that only server components render always shows the published version. `withForgePress(config, { preview: false })` leaves the preview out.',
} satisfies ForgePressEntry<'page'>
