/** Generated by the webenv plugin from `.webenv/schema.ts` + `.webenv/content/*.ts`. */
declare module 'virtual:webenv/content' {
  export const schema: import('../core/schema').WebenvSchema
  export const content: Record<string, import('../content/reader').ContentRow[]>
}
