import type { IncomingMessage, ServerResponse } from 'node:http'
import type { UnpluginFactory } from 'unplugin'
import type { ContentRow } from './types/content/reader'
import type { WebenvSchema } from './types/core/schema'

import { Buffer } from 'node:buffer'
import { existsSync, readdirSync, readFileSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'
import process from 'node:process'
import { createUnplugin } from 'unplugin'
import { AUGMENTATION_FILE, CONTENT_DIR, ENDPOINT, SCHEMA_FILE, toComponentName } from './content/paths'
import { findRoot } from './content/root'
import { createWriter } from './content/writer/node'

export interface Options {
  /** Directory holding the `.webenv` folder. Defaults to the nearest ancestor that contains one. */
  root?: string
  /** Serve the editor write endpoint from the dev server. Defaults to `true`. */
  write?: boolean
}

const VIRTUAL_ID = 'virtual:webenv/content'
const RESOLVED_ID = `\0${VIRTUAL_ID}`

const AUGMENTATION = `// Generated by Webenv. Do not edit.
import type schema from './schema'

declare module 'webenv' {
  interface WebenvSchemaRegistry {
    schema: typeof schema
  }
}

export {}
`

/** Write the `webenv` module augmentation that types `query()` against the local schema. */
function writeAugmentation(root: string): void {
  const path = join(root, AUGMENTATION_FILE)
  const current = existsSync(path) ? readFileSync(path, 'utf8') : undefined
  if (current !== AUGMENTATION)
    writeFileSync(path, AUGMENTATION)
}

/** Content is exposed as one loader per component so a query only pulls the chunks it touches. */
function generate(root: string): string {
  const dir = join(root, CONTENT_DIR)
  const files = readdirSync(dir).filter(file => file.endsWith('.ts'))
  const entries = files.map(file => `  ${JSON.stringify(toComponentName(file))}: () => import(${JSON.stringify(join(dir, file))}),`)

  return [
    `export { default as schema } from ${JSON.stringify(join(root, SCHEMA_FILE))}`,
    `export const content = {\n${entries.join('\n')}\n}`,
    '',
  ].join('\n')
}

async function body(request: IncomingMessage): Promise<unknown> {
  const chunks: Buffer[] = []
  for await (const chunk of request)
    chunks.push(chunk as Buffer)

  return JSON.parse(Buffer.concat(chunks).toString('utf8'))
}

async function handle(root: string, request: IncomingMessage, response: ServerResponse): Promise<void> {
  const path = (request.url ?? '').slice(ENDPOINT.length)
  const writer = createWriter(root)

  if (path === '/schema')
    await writer.writeSchema(await body(request) as WebenvSchema)
  else if (path.startsWith('/content/'))
    await writer.writeContent(decodeURIComponent(path.slice('/content/'.length)), await body(request) as ContentRow[])
  else
    throw new Error(`unknown endpoint "${path}"`)

  response.statusCode = 204
  response.end()
}

export const unpluginFactory: UnpluginFactory<Options | undefined> = (options) => {
  let root = options?.root ?? findRoot(process.cwd())

  return {
    name: 'unplugin-webenv',

    vite: {
      configResolved(config) {
        root = options?.root ?? findRoot(config.root)
      },

      configureServer(server) {
        if (options?.write === false)
          return

        server.middlewares.use((request, response, next) => {
          if (request.method !== 'POST' || !request.url?.startsWith(`${ENDPOINT}/`))
            return next()

          handle(root, request, response).catch((error: unknown) => {
            response.statusCode = 500
            response.end(error instanceof Error ? error.message : String(error))
          })
        })
      },
    },

    buildStart() {
      writeAugmentation(root)
    },

    resolveId(id) {
      if (id === VIRTUAL_ID)
        return RESOLVED_ID
    },

    load(id) {
      if (id === RESOLVED_ID)
        return generate(root)
    },
  }
}

export const unplugin = /* #__PURE__ */ createUnplugin(unpluginFactory)

export default unplugin

export const vitePlugin = unplugin.vite
export const rollupPlugin = unplugin.rollup
export const rolldownPlugin = unplugin.rolldown
export const webpackPlugin = unplugin.webpack
export const rspackPlugin = unplugin.rspack
export const farmPlugin = unplugin.farm
export const bunPlugin = unplugin.bun
