import type { UnpluginFactory } from 'unplugin'

import { existsSync, readdirSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import process from 'node:process'
import { createUnplugin } from 'unplugin'

export interface Options {
  /** Directory holding the `.webenv` folder. Defaults to the nearest ancestor that contains one. */
  root?: string
}

const VIRTUAL_ID = 'virtual:webenv/content'
const RESOLVED_ID = `\0${VIRTUAL_ID}`
const WEBENV_DIR = '.webenv'
const CONTENT_DIR = `${WEBENV_DIR}/content`
const SCHEMA_FILE = `${WEBENV_DIR}/schema.ts`
const AUGMENTATION_FILE = `${WEBENV_DIR}/webenv.d.ts`

const AUGMENTATION = `// Generated by Webenv. Do not edit.
import type schema from './schema'

declare module 'webenv' {
  interface WebenvSchemaRegistry {
    schema: typeof schema
  }
}

export {}
`

function toComponentName(file: string): string {
  return file.replace(/\.ts$/, '').replace(/-(\w)/g, (_, char: string) => char.toUpperCase())
}

/** Walk up from `start` until a directory containing `.webenv` is found. */
function findRoot(start: string): string {
  for (let dir = start; ; dir = dirname(dir)) {
    if (existsSync(join(dir, WEBENV_DIR)))
      return dir
    if (dir === dirname(dir))
      return start
  }
}

/** Write the `webenv` module augmentation that types `query()` against the local schema. */
function writeAugmentation(root: string): void {
  const path = join(root, AUGMENTATION_FILE)
  const current = existsSync(path) ? readFileSync(path, 'utf8') : undefined
  if (current !== AUGMENTATION)
    writeFileSync(path, AUGMENTATION)
}

function generate(root: string): string {
  const dir = join(root, CONTENT_DIR)
  const files = readdirSync(dir).filter(file => file.endsWith('.ts'))

  const imports = files.map((file, index) => `import content${index} from ${JSON.stringify(join(dir, file))}`)
  const entries = files.map((file, index) => `  ${JSON.stringify(toComponentName(file))}: content${index},`)

  return [
    `import schema from ${JSON.stringify(join(root, SCHEMA_FILE))}`,
    ...imports,
    '',
    'export { schema }',
    `export const content = {\n${entries.join('\n')}\n}`,
    '',
  ].join('\n')
}

export const unpluginFactory: UnpluginFactory<Options | undefined> = (options) => {
  let root = options?.root ?? findRoot(process.cwd())

  return {
    name: 'unplugin-webenv',

    vite: {
      configResolved(config) {
        root = options?.root ?? findRoot(config.root)
      },
    },

    buildStart() {
      writeAugmentation(root)
    },

    resolveId(id) {
      if (id === VIRTUAL_ID)
        return RESOLVED_ID
    },

    load(id) {
      if (id === RESOLVED_ID)
        return generate(root)
    },
  }
}

export const unplugin = /* #__PURE__ */ createUnplugin(unpluginFactory)

export default unplugin

export const vitePlugin = unplugin.vite
export const rollupPlugin = unplugin.rollup
export const rolldownPlugin = unplugin.rolldown
export const webpackPlugin = unplugin.webpack
export const rspackPlugin = unplugin.rspack
export const esbuildPlugin = unplugin.esbuild
export const farmPlugin = unplugin.farm
export const bunPlugin = unplugin.bun
