import type { IncomingMessage, ServerResponse } from 'node:http'
import type { UnpluginFactory } from 'unplugin'
import type { MediaConfig } from './types/config/media'
import type { ContentRow } from './types/content/reader'
import type { WebenvSchema } from './types/core/schema'

import { Buffer } from 'node:buffer'
import { existsSync, readdirSync, readFileSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'
import process from 'node:process'
import { createUnplugin } from 'unplugin'
import { resolveMedia } from './content/media'
import { createMediaStore } from './content/media/node'
import { AUGMENTATION_FILE, CONTENT_DIR, ENDPOINT, SCHEMA_FILE, toComponentName } from './content/paths'
import { findRoot } from './content/root'
import { createWriter } from './content/writer/node'

export interface Options {
  /** Directory holding the `.webenv` folder. Defaults to the nearest ancestor that contains one. */
  root?: string
  /** Serve the editor write endpoint from the dev server. Defaults to `true`. */
  write?: boolean
  /** Where uploads are written and how content references them. Defaults to `public/uploads` served at `/uploads`. */
  media?: MediaConfig
}

const VIRTUAL_ID = 'virtual:webenv/content'
const RESOLVED_ID = `\0${VIRTUAL_ID}`

const AUGMENTATION = `// Generated by Webenv. Do not edit.
import type schema from './schema'

declare module 'webenv' {
  interface WebenvSchemaRegistry {
    schema: typeof schema
  }
}

export {}
`

/** Write the `webenv` module augmentation that types `query()` against the local schema. */
function writeAugmentation(root: string): void {
  const path = join(root, AUGMENTATION_FILE)
  const current = existsSync(path) ? readFileSync(path, 'utf8') : undefined
  if (current !== AUGMENTATION)
    writeFileSync(path, AUGMENTATION)
}

/** Content is exposed as one loader per component so a query only pulls the chunks it touches. */
async function generate(root: string, local: boolean, config?: MediaConfig): Promise<string> {
  const dir = join(root, CONTENT_DIR)
  const files = readdirSync(dir).filter(file => file.endsWith('.ts'))
  const entries = files.map(file => `  ${JSON.stringify(toComponentName(file))}: () => import(${JSON.stringify(join(dir, file))}),`)

  const media = resolveMedia(config)
  const assets = await createMediaStore(root, config).list()

  return [
    `export const local = ${local}`,
    `export const media = ${JSON.stringify({ url: media.url, maxSize: media.maxSize, assets })}`,
    `export { default as schema } from ${JSON.stringify(join(root, SCHEMA_FILE))}`,
    `export const content = {\n${entries.join('\n')}\n}`,
    '',
  ].join('\n')
}

async function bytes(request: IncomingMessage): Promise<Buffer> {
  const chunks: Buffer[] = []
  for await (const chunk of request)
    chunks.push(chunk as Buffer)

  return Buffer.concat(chunks)
}

async function body(request: IncomingMessage): Promise<unknown> {
  return JSON.parse((await bytes(request)).toString('utf8'))
}

function json(response: ServerResponse, payload: unknown): void {
  response.statusCode = 200
  response.setHeader('content-type', 'application/json')
  response.end(JSON.stringify(payload))
}

async function media(options: Options | undefined, root: string, path: string, request: IncomingMessage, response: ServerResponse): Promise<void> {
  const store = createMediaStore(root, options?.media)
  const name = decodeURIComponent(path.slice('/media/'.length))

  if (request.method === 'GET')
    return json(response, await store.list())

  if (request.method !== 'DELETE')
    return json(response, await store.write({ name, data: await bytes(request) }))

  await store.remove(name)

  response.statusCode = 204
  response.end()
}

async function handle(options: Options | undefined, root: string, request: IncomingMessage, response: ServerResponse): Promise<void> {
  const path = (request.url ?? '').slice(ENDPOINT.length)
  const writer = createWriter(root)

  if (path === '/media' || path.startsWith('/media/'))
    return media(options, root, path, request, response)

  if (path === '/schema')
    await writer.writeSchema(await body(request) as WebenvSchema)
  else if (!path.startsWith('/content/'))
    throw new Error(`unknown endpoint "${path}"`)
  else if (request.method === 'DELETE')
    await writer.removeContent(decodeURIComponent(path.slice('/content/'.length)))
  else
    await writer.writeContent(decodeURIComponent(path.slice('/content/'.length)), await body(request) as ContentRow[])

  response.statusCode = 204
  response.end()
}

export const unpluginFactory: UnpluginFactory<Options | undefined> = (options) => {
  let root = options?.root ?? findRoot(process.cwd())
  let local = false

  return {
    name: 'unplugin-webenv',

    vite: {
      configResolved(config) {
        root = options?.root ?? findRoot(config.root)
        local = config.command === 'serve' && options?.write !== false
      },

      configureServer(server) {
        if (options?.write === false)
          return

        server.middlewares.use((request, response, next) => {
          const method = request.method ?? ''
          const handled = method === 'POST' || method === 'DELETE' || method === 'GET'

          if (!handled || !request.url?.startsWith(`${ENDPOINT}/`))
            return next()

          handle(options, root, request, response).catch((error: unknown) => {
            response.statusCode = 500
            response.end(error instanceof Error ? error.message : String(error))
          })
        })
      },
    },

    buildStart() {
      writeAugmentation(root)
    },

    resolveId(id) {
      if (id === VIRTUAL_ID)
        return RESOLVED_ID
    },

    load(id) {
      if (id === RESOLVED_ID)
        return generate(root, local, options?.media)
    },
  }
}

export const unplugin = /* #__PURE__ */ createUnplugin(unpluginFactory)

export default unplugin

export const vitePlugin = unplugin.vite
export const rollupPlugin = unplugin.rollup
export const rolldownPlugin = unplugin.rolldown
export const webpackPlugin = unplugin.webpack
export const rspackPlugin = unplugin.rspack
export const farmPlugin = unplugin.farm
export const bunPlugin = unplugin.bun
